schema:
  ./server/src/schema/index.ts:
    require: ts-node/register
documents: "./client/src/graphql/**/*.ts"
extensions:
  # Graphback configuration
  graphback:
    ##  Input schema
    model: ./model
    ## Global configuration for CRUD generator
    crudSpec:
      create: true
      update: true
      findAll: true
      find: true
      delete: false
      subCreate: false
      subUpdate: false
      subDelete: false
      disableGen: false
    ## Codegen plugins
    plugins:
        graphback-codegen-schema:
          format: 'gql'
          outputPath: ./server/src/schema
          outputFileName: 'generated'
        graphback-codegen-client:
          format: 'ts'
          outputPath: ./client/src/graphql
        graphback-codegen-resolvers:
          format: ts
          outputPath: ./server/src/resolvers
          types:
            resolverRootLocation: ../../generated-types
            resolverRootType: Resolvers
    ## Knex DB Migration config
    knexdb:
      ## See knex.js config format
      dbConfig:
        user: postgresql
        password: postgres
        database: users
        host: localhost
        port: 55432
      database: pg
  codegen:
    ./server/src/generated-types.ts:
      plugins:
        - typescript
        - typescript-resolvers
    ./client/src/generated-types.tsx:
      plugins:
        - typescript
        - typescript-operations
        - typescript-react-apollo
      config:
        withComponent: false
        withHOC: false
        withHooks: true
